parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: ./
extends:
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "prettier/standard"
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/indent":
    - error
    - 2
env:
  browser: true
globals:
  chrome: true
