parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: ./
extends:
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "prettier/standard"
plugins:
  - "@typescript-eslint"
settings:
  node:
    tryExtensions:
      - .js
      - .ts
      - .json
      - .node
rules:
  "@typescript-eslint/indent": off
  "@typescript-eslint/member-delimiter-style": off
  "@typescript-eslint/explicit-member-accessibility": warn
env:
  browser: true
globals:
  chrome: true
