coverage:
  ignore:
    - "modules/*/test.ts"
    - "test/*"
  status:
      patch:
        default:
          enabled: false
      project:
        default:
          enabled: true
          target: 90%
parsers:
  javascript:
    enable_partials: yes

